"""Alter stock_movement quantity column to NUMERIC

Revision ID: a1b2c3d4e5f6
Revises: 9bc675d9f120
Create Date: 2025-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9bc675d9f120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        # Change quantity column from VARCHAR to NUMERIC
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        # Revert quantity column back to VARCHAR
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
