"""add spolige created_by column

Revision ID: bca9aa4981b8
Revises: 9abc239df951
Create Date: 2026-04-21 13:29:07.597348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bca9aa4981b8'
down_revision = '9abc239df951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('spolige', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('remaining_stock',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.alter_column('remaining_stock',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('spolige', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receipt_num', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('seller_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seller_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('seller_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('buyer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('buyer_contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('payment', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('items', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtotal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='receipts_pkey'),
    sa.UniqueConstraint('receipt_num', name='receipts_receipt_num_key')
    )
    # ### end Alembic commands ###
